kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: pwx-prometheus-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
   io_priority: "high"
   snap_schedule: "daily=12:00,2"
allowVolumeExpansion: true
reclaimPolicy: Retain
