kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: pwx-minio-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   io_profile: "sequential"
   io_priority: "high"
   group: "minio"
allowVolumeExpansion: true
reclaimPolicy: Retain
