apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: helloworld
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app.kubernetes.io/name: helloworld
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: helloworld
