kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-repl3-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   io_profile: "db"
   priority_io: "high"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-mariadb-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: px-repl3-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      schedulerName: stork
      containers:
      - name: mariadb
        image: mariadb
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: MYSQL_USER
          value: mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: password.txt
        - name: MYSQL_DATABASE
          value: pxdemo
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: password.txt
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: px-mariadb-pvc