apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-namespaces-global
subjects:
- kind: User
  name: jane # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: joe # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
 kind: ClusterRole
 name: namespace-reader
 apiGroup: rbac.authorization.k8s.io
