apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: namespace-reader
rules:
 - apiGroups: ["*"]
   resources: ["namespaces", "clusterroles", "clusterrolebindings", "persistentvolumes"]
   verbs: ["get", "watch", "list"]
