kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: middleware
  name: deployment-manager
rules:
- apiGroups: ["", "extensions", "apps", "rbac.authorization.k8s.io", "networking.k8s.io", "batch"]
  resources: ["deployments", "replicasets", "pods", "services", "roles", "rolebindings", "*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
